# Generated by Django 4.0.1 on 2022-06-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
